#!/bin/bash
# Make all the libraries in src.

usage() 
{
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE
usage: ${0##*/} [OPTION]
  
options:
  -cleanall    Clean all
  -debug       Compile in debug mode
  -help        This usage

USAGE
    exit 1
}

debug=0
cleanall=0

# parse options
while [ "$#" -gt 0 ]
do
   case "$1" in
   -h | -help)
      usage
      ;;
   -debug)
      debug=1
      shift 1   
      ;;
   -cleanall)
      cleanall=1
      shift 1
      ;;
   --)
      shift
      break
      ;;
   -*)
      usage "invalid option '$1'"
      ;;
   *)
      break
      ;;
   esac
done

odesolvers=(cvode cvodes radau kinsol ida)
io=(camxml comostrings)
folders=(sprogc geometry camflow sweepc mopsc brush)

if [ $cleanall -eq 1 ]; then
    for element in ${odesolvers[@]}
    do
        make --directory=src/odesolvers/$element -s --file="new"$element"Makefile" cleanlibs
    done
    for element in ${io[@]}
    do
        make --directory=src/io/$element -s --file="new"$element"Makefile" cleanlibs
    done
    for element in ${folders[@]}
    do
        make --directory=src/$element -s --file="new"$element"Makefile" cleanlibs
    done
    exit
fi

echo "Make everything with debug set to $debug."

echo "Make ODE solver libraries:"
odesolvers=(cvode cvodes radau kinsol ida)
for element in ${odesolvers[@]}
do
    make --directory=src/odesolvers/$element -s --file="new"$element"Makefile" clean all debug=$debug
    if [ $? -gt 0 ] ; then
        echo make $element failed
        exit
    else
        echo make $element success
    fi
done

echo "Make IO libraries:"
io=(camxml comostrings)
for element in ${io[@]}
do
    make --directory=src/io/$element -s --file="new"$element"Makefile" clean all debug=$debug
    if [ $? -gt 0 ] ; then
        echo make $element failed
        exit
    else
        echo make $element success
    fi
done

echo "Make the rest:"
folders=(sprogc geometry camflow sweepc mopsc brush)
for element in ${folders[@]}
do
    make --directory=src/$element -s --file="new"$element"Makefile" clean all debug=$debug
    if [ $? -gt 0 ] ; then
        echo make $element failed
        exit
    else
        echo make $element success
    fi
done
