### Write Input Files. 
# mops.inx

import sys, os, re
import xml.etree.ElementTree as ET
import xml.dom.minidom as DOM
# print pretty
def prettify(elem):
    """Return a pretty-printed XML string for the Element.
    """
    rough_string = ET.tostring(elem, 'utf-8')
    reparsed = DOM.parseString(rough_string)
    return reparsed.toprettyxml(indent="    ")

root = ET.Element('mops')
root.set('version', '2')
root.append(ET.Comment('Generated by writeMOPSinx.py for MOPS input file'))

runs = ET.SubElement(root, 'runs')
runs.text = str(2)
atol = ET.SubElement(root, 'atol')
atol.text= str(1.0e-17)
rtol = ET.SubElement(root, 'rtol')
rtol.text = str(1.0e-4)
maxm0 = ET.SubElement(root, 'maxm0')
maxm0.text = str(1000)
reactor = ET.SubElement(root, 'reactor')
reactor.set('type', 'batch')
reactor.set('constt', 'false')
reactor.set('constv', 'false')
reactor.set('id', 'TTIP_flame')
reactor.set('units', "mol/mol")
temperature = ET.SubElement(reactor, 'temperature')
temperature.set('units', "K")
pressure = ET.SubElement(reactor, 'pressure')
pressure.set('units', 'bar')
component1 = ET.SubElement(reactor, 'component')
component1.set('id', "C12H28O4TI")
component2 = ET.SubElement(reactor, 'component')
component2.set('id', "AR")
component3 = ET.SubElement(reactor, 'component')
component3.set('id', "O2")
component4 = ET.SubElement(reactor, 'component')
component4.set('id', "C2H4")


# Time Intervals:
timeintervals = ET.SubElement(root, 'timeintervals')
start = ET.SubElement(timeintervals,'start')
start.text = str(0)
time_i = ET.SubElement(timeintervals,'time')
time_i.text=str(0.5)
time_i.set('steps', str(1000))
time_i.set('splits', str(10))


# Terminal Output:
output = ET.SubElement(root, 'output')
statsbound = ET.SubElement(output, 'statsbound')
lower = ET.SubElement(statsbound, 'lower')
lower.text= str(0)
upper = ET.SubElement(statsbound, 'upper')
upper.text= str(1.0e30)
console = ET.SubElement(output, 'console')
console.set('interval', str(1))
console.set('msgs',"True")
tabular = ET.SubElement(console, 'tabular')
column1 = ET.SubElement(tabular, 'column')
column1.set("fmt","sci")
column1.text="time"
column2 = ET.SubElement(tabular, 'column')
column2.set("fmt","float")
column2.text="#sp"
column3 = ET.SubElement(tabular, 'column')
column3.set("fmt","sci")
column3.text="C12H28O4TI"
column4 = ET.SubElement(tabular, 'column')
column4.set("fmt","sci")
column4.text="M0"
column5 = ET.SubElement(tabular, 'column')
column5.set("fmt","sci")
column5.text="M1"
column6 = ET.SubElement(tabular, 'column')
column6.set("fmt","sci")
column6.text="T"
ptrack = ET.SubElement(output, 'ptrack')
ptrack.set('enable', 'True')
ptrack.set('ptcount', str(1))
filename = ET.SubElement(output, 'filename')


# print to terminal and write to file:
print(prettify(root))
with open('test_mops.inx','w') as f:
    # overwrite if anything is there
    f.write(prettify(root))

